### ISSUE TITLE
Specification is not yet complete: for v1 we need to support the following list of PGNs and sentences*

### ISSUE THREAD

**Issue by fabdrol** [SignalK/specification#100]
As discussed on Slack and the mailing list, the specification as it stands right now doesn't support all PGNs and sentences we should support in v1. This GH issue is an attempt to collect and list all PGNs + sentences - both supported and unsupported. Supported messages will be ~~crossed off~~.

How this will work: below is an (initial) list of 0183 sentences and PGNs, based on the list of PGNs decoded by canboat and the 0183 sentences documentation from various online sources. This list is by no means complete. **Please post additions to the list in the comments, I'll add them to the list in the OP**.

*Note: I haven't yet crossed off any PGN and sentence, please provide input on which are supported and which are not, as well as on which PGNs or sentences should not be supported at all.*

PNGs                                                                  |0183 Sentences
----------------------------------------------------------------------|--------------
**65001** Bus #1 Phase C Basic AC Quantities                          |~~APB~~
**65002** Bus #1 Phase B Basic AC Quantities                          |~~DBT~~
**65003** Bus #1 Phase A Basic AC Quantities                          |~~GGA~~
**65004** Bus #1 Average Basic AC Quantities                          |~~GLL~~
**65005** Utility Total AC Energy                                     |~~HDM~~
**65006** Utility Phase C AC Reactive Power                           |~~HDT~~
**65007** Utility Phase C AC Power                                    |~~MWV~~
**65008** Utility Phase C Basic AC Quantities                         |~~RMC~~
**65009** Utility Phase B AC Reactive Power                           |~~VDM~~
**65010** Utility Phase B AC Power                                    |~~VDO~~
**65011** Utility Phase B Basic AC Quantities                         |~~VTG~~
**65012** Utility Phase A AC Reactive Power                           |**GSA**
**65013** Utility Phase A AC Power                                    |**GBS**
**65014** Utility Phase A Basic AC Quantities                         |**GSV**
**65015** Utility Total AC Reactive Power                             |**BWC**
**65016** Utility Total AC Power                                      |**ZDA**
**65017** Utility Average Basic AC Quantities                         |**AAM**
**65018** Generator Total AC Energy                                   |**BOD**
**65019** Generator Phase C AC Reactive Power                         |**RMB**
**65020** Generator Phase C AC Power                                  |**XTE**
**65021** Generator Phase C Basic AC Quantities                       |**DPT**
**65022** Generator Phase B AC Reactive Power                         |**MTW**
**65023** Generator Phase B AC Power                                  |**VLW**
**65024** Generator Phase B Basic AC Quantities                       |**VHW**
**65025** Generator Phase A AC Reactive Power                         |**HDG**
**65026** Generator Phase A AC Power                                  |**MWD**
**65027** Generator Phase A Basic AC Quantities                       |**XDR**
**65028** Generator Total AC Reactive Power                           |
**65029** Generator Total AC Power                                    |
**65030** Generator Average Basic AC Quantities                       |
**65536** Unknown fast-packet addressed                               |
**126983** Alert                                                      |
**126984** Alert Response                                             |
**126985** Alert Text                                                 |
**126986** Alert Configuration                                        |
**126987** Alert Threshold                                            |
**126988** Alert Value                                                |
**126992** System Time                                                |
**126993** Heartbeat                                                  |
**126996** Product Information                                        |
**126998** Configuration Information                                  |
**127233** Man Overboard Notification                                 |
**127237** Heading/Track control                                      |
**127245** Rudder                                                     |
**127250** Vessel Heading                                             |
**127251** Rate of Turn                                               |
**127257** Attitude                                                   |
**127258** Magnetic Variation                                         |
**127488** Engine Parameters, Rapid Update                            |
**127489** Engine Parameters, Dynamic                                 |
**127493** Transmission Parameters, Dynamic                           |
**127496** Trip Parameters, Vessel                                    |
**127497** Trip Parameters, Engine                                    |
**127498** Engine Parameters, Static                                  |
**127501** Binary Switch Bank Status                                  |
**127502** Switch Bank Control                                        |
**127503** AC Input Status                                            |
**127504** AC Output Status                                           |
**127505** Fluid Level                                                |
**127506** DC Detailed Status                                         |
**127507** Charger Status                                             |
**127508** Battery Status                                             |
**127509** Inverter Status                                            |
**127510** Charger Configuration Status                               |
**127511** Inverter Configuration Status                              |
**127512** AGS Configuration Status                                   |
**127513** Battery Configuration Status                               |
**127514** AGS Status                                                 |
**128259** Speed                                                      |
**128267** Water Depth                                                |
**128275** Distance Log                                               |
**128520** Tracked Target Data                                        |
**129025** Position, Rapid Update                                     |
**129026** COG & SOG, Rapid Update                                    |
**129027** Position Delta, Rapid Update                               |
**129028** Altitude Delta, Rapid Update                               |
**129029** GNSS Position Data                                         |
**129033** Time & Date                                                |
**129038** AIS Class A Position Report                                |
**129039** AIS Class B Position Report                                |
**129040** AIS Class B Extended Position Report                       |
**129044** Datum                                                      |
**129045** User Datum                                                 |
**129283** Cross Track Error                                          |
**129284** Navigation Data                                            |
**129285** Navigation - Route/WP Information                          |
**129291** Set & Drift, Rapid Update                                  |
**129301** Navigation - Route / Time to+from Mark                     |
**129302** Bearing and Distance between two Marks                     |
**129538** GNSS Control Status                                        |
**129539** GNSS DOPs                                                  |
**129540** GNSS Sats in View                                          |
**129541** GPS Almanac Data                                           |
**129542** GNSS Pseudorange Noise Statistics                          |
**129545** GNSS RAIM Output                                           |
**129546** GNSS RAIM Settings                                         |
**129547** GNSS Pseudorange Error Statistics                          |
**129549** DGNSS Corrections                                          |
**129550** GNSS Differential Correction Receiver Interface            |
**129551** GNSS Differential Correction Receiver Signal               |
**129556** GLONASS Almanac Data                                       |
**129792** AIS DGNSS Broadcast Binary Message                         |
**129793** AIS UTC and Date Report                                    |
**129794** AIS Class A Static and Voyage Related Data                 |
**129795** AIS Addressed Binary Message                               |
**129796** AIS Acknowledge                                            |
**129797** AIS Binary Broadcast Message                               |
**129798** AIS SAR Aircraft Position Report                           |
**129799** Radio Frequency/Mode/Power                                 |
**129800** AIS UTC/Date Inquiry                                       |
**129801** AIS Addressed Safety Related Message                       |
**129802** AIS Safety Related Broadcast Message                       |
**129803** AIS Interrogation                                          |
**129804** AIS Assignment Mode Command                                |
**129805** AIS Data Link Management Message                           |
**129806** AIS Channel Management                                     |
**129807** AIS Class B Group Assignment                               |
**129808** DSC Call Information                                       |
**129809** AIS Class B static data (msg 24 Part A)                    |
**129810** AIS Class B static data (msg 24 Part B)                    |
**130060** Label                                                      |
**130061** Channel Source Configuration                               |
**130064** Route and WP Service - Database List                       |
**130065** Route and WP Service - Route List                          |
**130066** Route and WP Service - Route/WP-List Attributes            |
**130067** Route and WP Service - Route - WP Name & Position          |
**130068** Route and WP Service - Route - WP Name                     |
**130069** Route and WP Service - XTE Limit & Navigation Method       |
**130070** Route and WP Service - WP Comment                          |
**130071** Route and WP Service - Route Comment                       |
**130072** Route and WP Service - Database Comment                    |
**130073** Route and WP Service - Radius of Turn                      |
**130074** Route and WP Service - WP List - WP Name & Position        |
**130306** Wind Data                                                  |
**130310** Environmental Parameters                                   |
**130311** Environmental Parameters                                   |
**130312** Temperature                                                |
**130313** Humidity                                                   |
**130314** Actual Pressure                                            |
**130315** Set Pressure                                               |
**130316** Temperature Extended Range                                 |
**130320** Tide Station Data                                          |
**130321** Salinity Station Data                                      |
**130322** Current Station Data                                       |
**130323** Meteorological Station Data                                |
**130324** Moored Buoy Station Data                                   |
**130560** Payload Mass                                               |
**130567** Watermaker Input Setting and Status                        |
**130576** Small Craft Status                                         |
**130577** Direction Data                                             |
**130578** Vessel Speed Components                                    |
**130816** Manufacturer Proprietary fast-packet non-addressed         |

**Comment by fabdrol** [comment]
@canboat I used the `pgns.json` file as an input for the PGN list. Are there PGNs that can be taken of the list completely?

**Comment by canboat** [comment]
All manufacturer specific PGNs can be removed. That is anything starting with regex `[A-z]+: `

**Comment by canboat** [comment]
Also all CAN bus internal messaging: 59392, 59904, 60928, 61184, 61440, 65240, 65280, 126208, 126464, 126720, 126976.

**Comment by fabdrol** [comment]
Thanks @canboat, list has been updated.

**Comment by rob42** [comment]
Remeber we can do v1 without half of these as more pgns = additions, eg v1.1, v1.2 etc. Since key additions are generally non-breaking changes we can safely allow them. We do need to get the high level structure right though.

**Comment by tkurki** [comment]
I don't see much value in this issue - it is not usable for tracking progress because there is no granularity and nobody has updated it for months. I'd like to close it.

**Comment by tkurki** [comment]
The schema is in pretty decent shape in terms of supporting a reasonable NMEA coverage. This is issue has not been super useful in tracking sentence/pgn support, which is more driven by n2k-signalk and  signalk-parser-nmea0183 Development and should be tracked there.
