### ISSUE TITLE
Easy to use, localizable units & names extracted from schema

### ISSUE THREAD

**Issue by tkurki** [SignalK/specification#111]
There is the manually created, easy to use and localizable file that contains short & long names and unit  for Signal K data items.

https://github.com/SignalK/specification/blob/master/i18n/en.json

Now that units are embedded in the schema we should produce this file from the schema automatically. English versions of short & long names should probably be embedded in the schema.

**Comment by rob42** [comment]
Good by me - just for the record, the file naming should follow the common [locale]_[variant]_[sub-variant].json format, so I can mod this to en_nz.js. Then when looking for files, we trim and retry, `en_nz.js` > `en.js`

**Comment by timmathews** [comment]
How about just wrapping the localization data in a locale object:

```
"en_US": {
  "alarms.anchorAlarmMethod": { },
  "alarms.anchorAlarmState": { }
}
```

This is the approach that RoR takes and it seems to work pretty well. That way it doesn't really matter what the files are called and you can even split up the localization among many files and just merge the objects.

**Comment by tkurki** [comment]
No pull for localisation and I am not sure if this should be part of the spec or an external resource, maintained separately and just depending on the schema / keys list.
