### ISSUE TITLE
What is a "self" reference for a server not located on a vessel?

### ISSUE THREAD

**Issue by jboynes** [SignalK/specification#150]
[`signalk.json`](https://github.com/SignalK/specification/blob/master/schemas/signalk.json#L8) specifies that a `self` property is required and holds the key for "this vessel." What should this refer to if the server is not running on a vessel or applies to several vessels?

For example, consider a SignalK server running in the head office of a company with a fleet, or in the charter base of a charter fleet. Would that server be allocated/invent a URL or UUID and have no or an empty `vessel` entry?

Should we simply make `self` optional?

**Comment by tkurki** [comment]
Yes.

**Comment by tkurki** [comment]
In fact it is already optional.
