### ISSUE TITLE
Automatic triggering of Delta Stream via URL request

### ISSUE THREAD

**Issue by sumps** [SignalK/specification#213]
There have been some inconsistencies in the way Delta File Subscription were documented on http://signalk.org and the way that the Node and Java Servers currently behave. To improve and standardise the way a client opens a websocket and subscribes to Delta Updates, we are proposing the following three URLs that can be called to initiate a websocket...

1)      ws://hostname/signalk/v1/stream?subscribe=self
2)      ws://hostname/signalk/v1/stream?subscribe=all
3)      ws://hostname/signalk/v1/stream?subscribe=none

To make it really easy for a simple client to initiate a websocket and subscribe to all Self updates without even knowing the MMSI number or UUID of Self, we have made the Self subscription the default and as such it can be triggered by just requesting...

ws://hostname/signalk/v1/stream

Which is the end point pointed to by http://hostname/signalk

The minimum that a simple client has to do to initiate a websocket and receive all of the Delta updates for Self is; call http://hostname/signalk to return the websocket end point URL and then request ws://hostname/signalk/v1/stream

If the client wishes to open a websocket and receive Delta updates for all vessels including Self, they can call the URL in 2) and if they want to setup a custom subscription, they can send the URL in 3) at which point the server/gateway should start sending the heartbeat message once per second and wait for the client to send a subscription command as per the current defined method - see http://signalk.org/developers/subscription_protocol.html

**Comment by tkurki** [comment]
See the linked issue.
