### ISSUE TITLE
Update tutorials to include node installation on older RPis

### ISSUE THREAD

**Issue by SailorMax59** [SignalK/specification#220]
Hello Teppo,
Thanks for the very helpful tutorial. If not already described in another place, I would like to help other signalK users. Nodejs seems to be very picky regarding its version used on ARM, there is some discussion on that on the web. When following the tutorial, I was getting “segmentation fault” after installing nodejs and probing it with node –v. The cure was to install node-v4.4.4-linux-armv6l.tar.gz from www.nodejs.org/downloads. The node-v4.4.4-linux-armv7l.tar.gz did also produce the “segmentation fault” error.

Regards Matthias

Raspi B+ V1.2 (2014)
Raspian Jessie

**Comment by canboat** [comment]
Matthias, an original RPi is ARM v6, not v7, so that makes full sense that an ARM v7 compiled version doesn't work for you.

**Comment by tkurki** [comment]
@SailorMax59  which tutorial did you use? The wiki tutorials you can update yourself by adding instructions for ARM v6 node installation.

FYI there are Ansible tasks for installing current Node on RPi, see https://github.com/tkurki/marinepi-provisioning/tree/master/roles/node/tasks

I rewrote the issue title to better reflect what needs to be done.

**Comment by SailorMax59** [comment]
Hello Teppo,

I used the github tutorial at https://github.com/SignalK/specification/wiki/Raspberry-Pi-Installation-(Node-Server).

 

Thanks for your quick response !!!

 

Matthias

Von: Teppo Kurki [mailto:notifications@github.com] 
Gesendet: Sonntag, 15. Mai 2016 21:40
An: SignalK/specification <specification@noreply.github.com>
Cc: SailorMax59 <sailor_max@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [SignalK/specification] Update tutorials to include node installation on order RPis (#220)

 

@SailorMax59 <https://github.com/SailorMax59>  which tutorial did you use? The wiki tutorials you can update yourself by adding instructions for ARM v6 node installation.

FYI there are Ansible tasks for installing current Node on RPi, see https://github.com/tkurki/marinepi-provisioning/tree/master/roles/node/tasks

I rewrote the issue title to better reflect what needs to be done.
