### ISSUE TITLE
Missing Units in Doc

### ISSUE THREAD

**Issue by tkurki** [SignalK/specification#258]
For some keys schema has units but it is missing in docs.

https://github.com/SignalK/specification/blob/master/schemas/groups/navigation.json#L373-L382

http://signalk.org/specification/master/keys/#vesselsregexpnavigationheadingmagnetic

**Comment by joabakk** [comment]
I also noticed electrical.batteries.0.voltage showed up without description or unit

**Comment by fabdrol** [comment]
I'll have a look when I get the chance

**Comment by tkurki** [comment]
When you have a reference it replaces all the siblings at the same level, so if you have 

```
    "headingMagnetic": {
      "$ref": "../definitions.json#/definitions/numberValue",
      "description": "Current magnetic heading of the vessel",
      "units": "rad"
    },
```
`description` and `units` are never handled: https://github.com/SignalK/specification/blob/ccbf79301cf01c61bf0b68cc601f782b8797d0b0/scripts/processSchemaFiles.js#L348-L352

**Comment by tkurki** [comment]
@joabakk there is no `electrical.batteries.0.voltage` in the doc at http://signalk.org/specification/master/keys/ ???

**Comment by joabakk** [comment]
Ok it may be an implementation fault on my side. What would battery voltages' addresses be?

This is strictly rs11 -> canboat -> signal k

**Comment by timmathews** [comment]
`electrical.batteries.0.voltage` exists, it's just another victim of the `$ref` overwriting siblings.
