### ISSUE TITLE
Object valued properties structure in docs keys list

### ISSUE THREAD

**Issue by tkurki** [SignalK/specification#273]
Examples:

http://signalk.org/specification/master/keys/#vesselsregexpnavigationposition
http://signalk.org/specification/master/keys/#vesselsregexpenvironmentcurrent

There should be information about the structure and property units.

**Comment by thomasonw** [comment]
Please also make sure to add N/S and E/W conventions - what ever they may  be.  (ala, using negative number for W if that is how they are defined)
