### ISSUE TITLE
Key AIS data not supported

### ISSUE THREAD

**Issue by sumps** [SignalK/specification#317]
Whilst testing the latest iKommunicate build, it has become apparent that the schema is still lacking some key AIS data. Currently we have no way of identifying if a vessel is a Class A or Class B AIS target and also what AIS category of vessel it is.

I would suggest that AIS Class should perhaps be stored in the Communications group and the Category of vessel stored in the Design group but I am happy to hear the views of others. It would be nice to get this pushed through in time for V1 though as I think it is an important issue for the correct display and filtering of vessels.

The AIS Class would be automatically populated based on the AIS Message type or PGN, whilst the Category of vessel would be populated from the "Ship/Cargo Type" field in the relevant PGN or NMEA Sentence.

![vessel types](https://cloud.githubusercontent.com/assets/10165637/21701327/eb8315e6-d39c-11e6-858e-b3a0f39ee992.png)

**Comment by rob42** [comment]
Sounds good. Can you make a pull request to suit?

**Comment by tkurki** [comment]
AIS class implemented in #562 as sensors.ais.class.

**Comment by tkurki** [comment]
AIS ship type is `design.aisShipType`, both as string and as number.

**Comment by tkurki** [comment]
https://github.com/SignalK/specification/blob/3ccbd2a904698c6479289a0202311da591f04a68/schemas/groups/design.json#L39-L350
