### ISSUE TITLE
Outside light levels (Lux)

### ISSUE THREAD

**Issue by toqduj** [SignalK/specification#318]
I'm making another MKR1000-based wireless SignalK sensor for mounting on deck, this one containing a humidity, pressure, temperature and light level sensor. I noticed there's no entry in the SignalK specifications for outside light levels. Such a reading would be useful, for example for automatically dimming instrument lights based on the available levels.

I'd suggest the following:
/vessels/<RegExp>/environment/outside/illuminance

Units: Lux (Lux)

Description: Current outside ambient light flux.

**Comment by tkurki** [comment]
Makes sense to me. Would you be able to add this to the schema file and add a test?

**Comment by toqduj** [comment]
I would, but I have no idea how (so would need to learn first), and too
swamped with work tasks to add this to my list. I'll have to take a rain
check on this one!

B.

**Comment by rob42** [comment]
I will do it tomorrow.

**Comment by rob42** [comment]
done and merged
