### ISSUE TITLE
Add a Date and Time for when Trip Log was Reset

### ISSUE THREAD

**Issue by sumps** [SignalK/specification#341]
In NMEA2000 the Date and Time that a Trip Log is reset is transmitted and we have supported this in iKommunicate. It would be good to include this in Signal K so that the data is not lost.

Add two new keys;

navigation.logResetDate
navigation.logResetTime

**Comment by rob42** [comment]
@paul, I created a trip object, and combined date and time.

**Comment by tkurki** [comment]
FIxed by #345
