### ISSUE TITLE
Subscription protocol: subscribe to parts of the data model

### ISSUE THREAD

**Issue by tkurki** [SignalK/specification#36]
A consumer should be able to tell the server which pieces of the SignalK data model it wants to receive updates for.

**Comment by tkurki** [comment]
https://github.com/SignalK/specification/wiki/Subscription-based-Streaming

**Comment by rob42** [comment]
Closing as we have this in https://github.com/SignalK/specification/wiki/Subscription-based-Streaming, and its implemented in the java server (not sure about node server).
Open a new issue if there is a specific use case not covered by the wiki page

**Comment by tkurki** [comment]
Node server is sadly lacking in this respect. I have started the implementation. Details at 
https://github.com/SignalK/signalk-server-node/issues/35
https://github.com/SignalK/signalk-server-node/commits/subscriptions
