### ISSUE TITLE
Support for vessel inventory

### ISSUE THREAD

**Issue by rob42** [SignalK/specification#37]
When recording a value we have a 'source' which includes various info about the values source.

Xavier suggested we may want make, model, even version etc, but this is too verbose for every value.

Hence we should consider having an inventory and just refer to the device when used in 'source'. The inventory also becomes useful for maintenance, insurance, customs, maybe lots of things.

So should we have vessels.[vessel].inventory.*

**Comment by fabdrol** [comment]
@rob42 is this synonymous for the `sensors` group?

**Comment by tkurki** [comment]
Too ambiguous, closing.
