### ISSUE TITLE
Coastline definition

### ISSUE THREAD

**Issue by joabakk** [SignalK/specification#370]
For routing purposes, coastline files are used so that the engine does not suggest sailing over land... These could be included (as geoJson?) under resources.

**Comment by joabakk** [comment]
https://www.ngdc.noaa.gov/mgg/shorelines/gshhs.html

**Comment by rob42** [comment]
Also worth a look here
http://www.naturalearthdata.com/downloads
I used these to create the coastal outlines in freeboard-sk

**Comment by tkurki** [comment]
I don't think this is a specification issue.

FYI World coastline is available in mbtiles format as a Node server plugin: https://www.npmjs.com/package/signalk-world-coastline-map

**Comment by joabakk** [comment]
Agreed
