### ISSUE TITLE
Message priority

### ISSUE THREAD

**Issue by rob42** [SignalK/specification#38]
In the simple case we generally have plenty of cheap bandwidth these days, but that doesnt mean all likely transport mediums will have the same. Data over HF or even satellite being an excellent example.

Possibly it can be dealt with by adding a "priority" key to the delta format for sending updates, and this could be honoured later by any transport medium that can deal with it. In the case of NMEA2000 it would map to their priority messages, in the case of TCP/IP, map to the native QOS capabilities. Maybe for HF it would filter to only critical data against a whitelist, then prioritise the sending queue.

**Comment by fabdrol** [comment]
@SignalK/owners is this something we want for version 1?

**Comment by sumps** [comment]
No, I think this should be a V2 feature. In reality, it will be the service that decides the priority of the data i.e. a crowd sourcing depth service will want depth and position or an Iridium satellite communication service will filter and compress the data that the service decides to support.

**Comment by tkurki** [comment]
I'll just repeat the gist of my earlier messages: there may be a need for priorities, but it is about communications, eg. between two or more parties and I don't believe there is no global overriding priority nor is there any pressing need to implement something within the Signal K model.

I'd say `vLater` or `vMaybe` (GH issue tags would work).
