### ISSUE TITLE
metadata: poor explanation of descriptions/names

### ISSUE THREAD

**Issue by bkp7** [SignalK/specification#408]
The are 4 free text descriptions: displayName, longName, shortName, description. There is no explanation as to what/where these should be used.

Possible solution: As a minimum an explanation and use case for each should be documented within the description in the schema. Possibly they are not all needed. eg. 'displayName': 'the text which appears on the face of a gauge to describe what it is measuring.', 'description': 'a more detailed explanation of the gauge/value in question and might for example be accessed by a user hovering over the gauge', etc. Any suggestions as to what the possible uses of longName and shortName are?

**Comment by tkurki** [comment]
I believe these originate from very early days of Signal K and not much deep thinking went into adding them. Makes sense to document their use, and even pruning might be justified.

Currently description comes automatically from the schema: http://node-master.signalk.org/signalk/v1/api/vessels/self/navigation/speedThroughWater/meta
