### ISSUE TITLE
Broken link in  specification/gitbook-docs/data_model.md 

### ISSUE THREAD

**Issue by lburaggi** [SignalK/specification#430]
The "Source" link in data_model.md page is broken (specification/blob/master/gitbook-docs/sources.md) the sources.md page doesn't exist

**Comment by tkurki** [comment]
The link was added in 246306620f6754cf832f636d6d50865af2c8f21d. 

@timmathews did you ever write sources.md? I can't remember there being one. Probably should write one, as this is the third or fourth question about it.

Ping @hkapanen.

**Comment by bkp7** [comment]
Also data_model.md has a section in it about sources and $sources indicating that you can use either one. This is not possible as $source is a mandatory requirement for all values (from common values in definitions.json)

**Comment by timmathews** [comment]
Yeah, kinda dropped the ball on the sources section. Writing one up now, a draft should be available shortly the a sources branch.

BTW, what is the point of [these lines in sources.json](https://github.com/SignalK/specification/blob/3222f988680c42d451fca742863845ee373082f8/schemas/groups/sources.json#L82-L88)?

**Comment by timmathews** [comment]
PR #432 addresses this
