### ISSUE TITLE
documentation: add notes on naming conventions for Pull Requests and Commits

### ISSUE THREAD

**Issue by bkp7** [SignalK/specification#450]
To ensure consistency of the change log, Pull Requests and Commit notes should be written in a consistent way. An explanation note should be drafted and added to the documentation under a 'developer notes' section.

Should this be restricted to just the Signal K standard or extended to other Signal K projects too?

**Comment by tkurki** [comment]
There is a PR for similar stuff in node server now. I'd be ready to close this issue, unless there is something still open?

**Comment by timmathews** [comment]
The PR has been merged. If we need to amend or expand the conventions, a new issue would be in order.
