### ISSUE TITLE
Human readable specification document usable in offline format

### ISSUE THREAD

**Issue by tkurki** [SignalK/specification#46]
To better promote Signal K we should create a nicely formatted, printable and downloadable version of the specification.

**Comment by woobagooba** [comment]
+1 to that.  Minimize the effort required to read/eval the spec.  Expectation when clicking through your site to Specification is ... well ... the specification is readily available.  It is not.  Cheers.

**Comment by fabdrol** [comment]
@woobagooba would you prefer a paper document over (better) online documentation?

**Comment by tkurki** [comment]
offline != paper. 

Current, clickable experience is not usable without a net connection, not random browsable and not searchable.

**Comment by woobagooba** [comment]
What Teppo said

PDF works

Thanks for checking

**Comment by fabdrol** [comment]
In that case, lets release a pdf upon every stable release - but not in between. Saves a lot of work and ensures that people with old PDFs develop against a certain stable version others are using too

**Comment by tkurki** [comment]
Fixed by #255, see http://signalk.org/specification/master/
