### ISSUE TITLE
README.md - Validation Errors inconsistent with documentation.

### ISSUE THREAD

**Issue by quietlyconfident** [SignalK/specification#472]
The readme.md file provides a copy-and-paste statement of the form: 

`echo '[some json]' | bin/validate.js`

And then shows what the error will be:

`Unknown property (not in schema):/vessels/230099999/navigation/courseOverGroundTru`

Unfortunately, this is not the result of running the command, the validator objects to ~ 8 different errors and spews out several pages of json-formatted errors.

This makes it really difficult, as a new user, to know whether you've got the thing installed properly or not.

**Comment by bkp7** [comment]
I have modified the example to use one of the test files and have shown the correct result.
