### ISSUE TITLE
missing: Drift

### ISSUE THREAD

**Issue by Dirk--** [SignalK/specification#519]
- Drift (drifting speed relative to ground) navigation.drift
- Set (drifting direction relative to true north) navigation.setTrue
- Set (drifting direction relative to magnetic north) navigation.setMagnetic

**Comment by Dirk--** [comment]
DFT and SET is a movement of the vessel ergo in navigation context.
might be caused by environment.current, environment.wind, environment.gravity, ...

environment.current.drift = speed of current relative to ground
environment.current.setTrue = direction of current relative to true north

**Comment by JonRowe** [comment]
In navigational terms, drift and set refer to current/tide, not wind or anything else.

**Comment by joabakk** [comment]
It is sufficient to have set and drift under environment. Your boat moves in the water, and the water moves under you. That is a result of the environment. The current use is to take the current as derived from speeds and course in e.g. NMEA0183 VDR into environment.current.

**Comment by Dirk--** [comment]
got it: https://en.wikipedia.org/wiki/Set_and_drift
Excuse my ignorance.
