### ISSUE TITLE
Clarify history snapshot URL in documentation

### ISSUE THREAD

**Issue by albert-smit** [SignalK/specification#553]
In the [specification](https://github.com/SignalK/specification/blame/master/gitbook-docs/rest_api.md#L71) the URL for history snapshot retrieval is specified as `/signalk/v1/snapshot`, but the node server implementation uses `/signalk/v1/api/snapshot`

Which one of these is the correct URL?

**Comment by tkurki** [comment]
Dammit, I thought I fixed this in https://github.com/SignalK/signalk-server-node/pull/684. Spec is correct, implementation should be fixed.

https://github.com/SignalK/signalk-server-node/issues/898
