### ISSUE TITLE
State of navigation lights (on/off) required by ColReg should be covered by SignalK spec

### ISSUE THREAD

**Issue by mgrouch** [SignalK/specification#612]
State of navigation lights (on/off) required by ColReg should be covered by SignalK spec

**Comment by tkurki** [comment]
Can you please first check the specification before adding issues?

https://signalk.org/specification/1.5.0/doc/vesselsBranch.html#vesselsregexpnavigationlights

https://github.com/SignalK/specification/blob/38147bc0ff7d16edb78d3bc55f131940799f528b/schemas/groups/navigation.json#L147-L171
