### ISSUE TITLE
Meta data for measurement units

### ISSUE THREAD

**Issue by MarkGlover** [SignalK/specification#66]
I can convert from SI units to any popular unit. I can not implement and maintain a signalK database at each client just to know what the measurement unit is.

**Comment by rob42** [comment]
Hi Mark, 
Could you elaborate more on the problem (your use case perhaps). When Signal K uses only SI units we mean a specific base SI unit. eg all velocity values are in meters per second, never km/hr. So its more a mapping of measurement type to SI unit you need, eg for velocity, temperature, distance, etc.

Also if you know the type of the destination (eg Nautical Miles) then the signal K source will be a 'distance', hence in meters

**Comment by fabdrol** [comment]
Closing for now. This has been addressed by (1) Rob's comment and (2) the addition of meta properties to the spec.
