### ISSUE TITLE
Review master branch - decide which groups will be stable and which will be experimental - document

### ISSUE THREAD

**Issue by fabdrol** [SignalK/specification#68]
@SignalK/contributors 

I've recently merged and closed a lot of (stale) pull requests. Running up to a 1st stable release, we need to review which groups will be included as `stable` (meaning that we can't just implement major breaking changes on them anymore) and which ones will be `experimental`. Please contribute your feedback in this thread, it'll serve as documentation.

**Comment by tkurki** [comment]
I'm going to close this, since it hasn't added any value and is just one more open issue.
