### ISSUE TITLE
Enum formatting

### ISSUE THREAD

**Issue by MariusVolkhart** [SignalK/specification#73]
Enums have various formats throughout the spec. For example, `waypoint.type` is all lower case while `navigation.state.value` starts with a upper case letter. What is the casing style that is preferred? I'd like to submit a PR with the appropriate changes.

**Comment by rob42** [comment]
Yes we should standardise. Preference possibly has more to do with your coding background than any real value - personally  The enum should be readable, but easily parsed and validated. Any objections to all lowercase?

**Comment by fabdrol** [comment]
I'm for all lowercase too. Capitalisation is easily forgotten, and causes sync issues.
