### ISSUE TITLE
bin/signalk-validate

### ISSUE THREAD

**Issue by mauroc** [SignalK/specification#97]
just getting my feet wet with SignalK (no pun intended), so apologies if the question is naive. 
The readme in the specification repo refers to the bin/signalk-validate script, though the file is not in the  repo. What am I missing? Thanks

**Comment by tkurki** [comment]
The doc & code were not in sync, it should read validate.js.

Fixed in f4dc37d3eee01e66dfd2fb92493d12cb51ed3816
